ext {

    dependencies = [
            skin_support                  : "com.github.NBXXF.Android-skin-support:skin-support:1.0.2",
            skin_support_appcompat        : "com.github.NBXXF.Android-skin-support:skin-support-appcompat:1.0.2",
            skin_support_constraint_layout: "com.github.NBXXF.Android-skin-support:skin-support-constraint-layout:1.0.2",
            skin_support_cardview         : "com.github.NBXXF.Android-skin-support:skin-support-cardview:1.0.2",
            skin_support_design           : "com.github.NBXXF.Android-skin-support:skin-support-design:1.0.2",
            // skin_support_circleimageview  : "com.github.NBXXF.Android-skin-support:circleimageview:1.0.2",
            //skin_support_flycotablayout   : "com.github.NBXXF.Android-skin-support:flycotablayout:1.0.2"

    ]

}