include ':lib_ktx'
include ':lib_i18n'
include ':lib_i18n:demo'
include ':lib_application'
include ':lib_utils'
include ':lib_rxjava:lib_rxlifecycledemo'
include ':lib_rxjava'
include ':room_demo'
include ':QTEnglish'
include ':lib_objectbox:lib_objectbox_demo'
include ':lib_view_ratio'
include ':lib_view_round'
include ':lib_view_gradient'
include ':lib_objectbox'
include ':lib_fileprovider'
include ':lib_adapter'
include ':lib_activityresult'
include ':lib_activityresult:demo'
include ':lib_permission'
include ':lib_permission:demo'
include ':lib_preferences'
include ':lib_preferencesGson'
include ':lib_preferencesMMKV'
include ':lib_snackbar'
include ':lib_effect'
include ':app'
include ':lib_http'
include ':lib_http:httpdemo'
include ':lib_log'
include ':lib_arch'
include ':lib_view'
include ':lib_viewbinding'
include ':lib_wechat'
include ':libs'
include ':lib_adapter:lib_adapter_demo'
//include ':ds_bridge'


//include ':optional:lib_audio'
//include ':optional:lib_audio:audio_demo'
//include ':optional:lib_audio:audio_demo_qq'

include ':optional:lib_wechat'
include ':optional:lib_objectbox'
include ':optional:lib_objectbox:lib_objectbox_demo'
include ':optional:lib_download'
include ':optional:lib_download_m3u8'
include ':optional:lib_download_m3u8:demo'
include ':optional:lib_preview'
include ':optional:lib_album'
include ':optional:lib_camera_wechat'
include ':optional:lib_camera_wechat:camera_demo'
include ':optional:lib_album:album_demo'
include ':optional:lib_preview:lib_previewer_demo'
include ':optional:lib_qrcode'
include ':optional:lib_qrcode:demo'
include ':optional:lib_glide'
include ':optional:lib_pinyin'
include ':optional:lib_mlkit'
include ':optional:lib_drouter'
include ':optional:lib_draggableView'
include ':optional:blockcanary:blockcanary-analyzer'
include ':optional:blockcanary:blockcanary-android'
include ':optional:blockcanary:blockcanary-android-no-op'
include ':optional:blockcanary:blockcanary-sample'
include ':optional:lib_flycoTabLayout'
include ':optional:lib_flycoTabLayout:FlycoTabLayoutDemo'
include ':optional:lib_profileinstaller'
include ':optional:lib_viewPager'
include ':optional:lib_viewPager:demo'

include ':optional:jbinder:lib_jbinder'
include ':optional:jbinder:lib_jbinder_compiler'
include ':optional:jbinder:sample-client'
include ':optional:jbinder:sample-library'
include ':optional:jbinder:sample-server'


include ':lib_effect:layout_anim_demo'
include ':lib_effect:ovserscroll_demo'
include ':lib_effect:animators_example'

def coreModulePaths = [
        'libs',
        'lib_activityresult',
        'lib_activityresult:demo',
        'lib_adapter',
        'lib_adapter:lib_adapter_demo',
        'lib_application',
        'lib_arch',
        'lib_effect',
        'lib_effect:layout_anim_demo',
        'lib_effect:ovserscroll_demo',
        'lib_effect:animators_example',
        'lib_fileprovider',
        'lib_http',
        'lib_http:httpdemo',
        'lib_ktx',
        'lib_log',
        'lib_permission',
        'lib_permission:demo',
        'lib_preferences',
        'lib_preferencesGson',
        'lib_preferencesMMKV',
        'lib_rxjava',
        'lib_rxjava:lib_rxlifecycledemo',
        'lib_snackbar',
        'lib_utils',
        'lib_view',
        'lib_view_gradient',
        'lib_view_ratio',
        'lib_view_round',
        'lib_viewbinding',
        'lib_i18n',
        'lib_i18n:demo',
]

coreModulePaths.each { modulePath ->
    project(":${modulePath}").projectDir = file("core/${modulePath.replace(':', '/')}")
}
