plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'kotlin-kapt'

}
def des = rootProject.ext.dependencies
android {
    compileSdk project.COMPILE_SDK_VERSION.toInteger()
    namespace = "com.xxf.rxjava"
    defaultConfig {
        minSdkVersion project.MIN_SDK_VERSION.toInteger()
        targetSdkVersion project.TARGET_SDK_VERSION.toInteger()
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        buildConfig = false
    }
}
dependencies {
    api libs.material
    api libs.rxJava
    api libs.rxAndroid
    implementation 'com.uber.autodispose2:autodispose-androidx-lifecycle:2.1.1'
    api 'com.uber.autodispose2:autodispose:2.1.1'
    implementation 'com.uber.autodispose2:autodispose-android:2.1.1'
}

ext {
    publishVersion = rootProject.xxfVersion
    publishGroup = rootProject.xxfGroup
    moduleName = project.name
    descContent = project.name
}

apply from: '../publish_maven.gradle'